# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 16:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20151224_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 28, 16, 8, 33, 951976, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 28, 16, 8, 33, 952950, tzinfo=utc)),
        ),
    ]
