# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20151229_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
