# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20160131_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='owner',
        ),
    ]
