# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_question_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='_question_text_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=markitup.fields.MarkupField(no_rendered_field=True),
        ),
    ]
