# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_exam_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='password',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
