# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20151228_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, max_length=45),
        ),
    ]
