# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='password',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
