# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20160102_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='password',
            field=models.CharField(blank=True, default=1234, max_length=10),
            preserve_default=False,
        ),
    ]
