# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.CharField(default='Examples', max_length=30),
            preserve_default=False,
        ),
    ]
