# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
