# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_exam_question_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(max_length=1),
        ),
    ]
