# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_studentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
