# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_auto_20160127_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='student',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='studentanswer',
            old_name='student',
            new_name='user',
        ),
    ]
