# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_auto_20160128_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
