# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20151216_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.CharField(default='', max_length=30),
        ),
    ]
