# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20151224_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='created',
            new_name='updated',
        ),
    ]
